# Generated by Django 5.2.3 on 2025-06-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paymenthistory_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
