# Generated by Django 5.1.4 on 2025-07-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_paymenthistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
