# Generated by Django 5.1.4 on 2025-07-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paymenthistory_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='proof',
        ),
    ]
