# Generated by Django 5.1.4 on 2025-07-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_digitalproduct'),
    ]

    operations = [
    ]
