# Generated by Django 5.1.4 on 2025-07-27 14:53

from django.db import migrations
from django.contrib.auth.models import User


def normalize_user_emails(apps, schema_editor):
    """
    Convert all user email addresses to lowercase for case-insensitive authentication
    """
    # Get the User model - using apps.get_model is recommended for migrations
    # but since User is from django.contrib.auth, we can use it directly
    for user in User.objects.all():
        if user.email:
            normalized_email = user.email.lower()
            if user.email != normalized_email:
                user.email = normalized_email
                user.save(update_fields=['email'])


def reverse_normalize_user_emails(apps, schema_editor):
    """
    Reverse migration - this is a no-op since we can't restore original casing
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20250727_0752'),
    ]

    operations = [
        migrations.RunPython(
            normalize_user_emails,
            reverse_normalize_user_emails,
        ),
    ]
