# Generated by Django 5.1.4 on 2025-07-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250727_0753'),
    ]

    operations = [
    ]
